sudo: required
services:
  - docker

before_install:
  - docker build -t yevhenkhabarov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yevhenkhabarov/react-test yarn test -- --coverage

after_success:
  - docker build -t yevhenkhabarov/multi-client ./client
  - docker build -t yevhenkhabarov/multi-nginx ./nginx
  - docker build -t yevhenkhabarov/multi-server ./server
  - docker build -t yevhenkhabarov/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yevhenkhabarov/multi-client
  - docker push yevhenkhabarov/multi-nginx
  - docker push yevhenkhabarov/multi-server
  - docker push yevhenkhabarov/multi-worker
