sudo: required
services:
  - docker

before_install:
  - docker build -t yevhenkhabarov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yevhenkhabarov/react-test yarn test -- --coverage

after_success:
  - docker build -t yevhenkhabarov/multi-client ./client
  - docker build -t yevhenkhabarov/multi-nginx ./nginx
  - docker build -t yevhenkhabarov/multi-server ./server
  - docker build -t yevhenkhabarov/multi-worker ./worker
